### ISSUE TITLE
Counter Simulators don't support step=0

### ISSUE THREAD

**Issue by ssclay** [nio-blocks/simulator#53]
If a CounterIntervalSimulator or CounterSafeSimulator are configured with a step=0, the service will not configure and the following error occurs:

```
[2018-01-11 19:39:25.742] NIO [ERROR] [TestPickle.new counter safe simulator] Failed to configure
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nio/util/runner.py", line 79, in do_configure
    self.configure(context)
  File "/Users/sclay/nio/projects/8080/blocks/simulator/generators/counter.py", line 34, in configure
    self.attr_value().step())
ValueError: range() arg 3 must not be zero
[2018-01-11 19:39:25.743] NIO [ERROR] [TestPickle.service] Failed to configure
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nio/util/runner.py", line 79, in do_configure
    self.configure(context)
  File "/usr/local/lib/python3.6/site-packages/nio/service/base.py", line 187, in configure
    block_context)
  File "/usr/local/lib/python3.6/site-packages/nio/service/base.py", line 221, in _create_and_configure_block
    block.do_configure(block_context)
  File "/usr/local/lib/python3.6/site-packages/nio/util/runner.py", line 79, in do_configure
    self.configure(context)
  File "/Users/sclay/nio/projects/8080/blocks/simulator/generators/counter.py", line 34, in configure
    self.attr_value().step())
ValueError: range() arg 3 must not be zero
[2018-01-11 19:39:25.744] NIO [WARNING] [TestPickle.ServiceLauncher] Service ended unexpectedly
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/niocore/core/service/launcher.py", line 103, in configure
    self._configure_service(self._context)
  File "/usr/local/lib/python3.6/site-packages/niocore/core/service/launcher.py", line 157, in _configure_service
    self._service.do_configure(service_context)
  File "/usr/local/lib/python3.6/site-packages/nio/util/runner.py", line 79, in do_configure
    self.configure(context)
  File "/usr/local/lib/python3.6/site-packages/nio/service/base.py", line 187, in configure
    block_context)
  File "/usr/local/lib/python3.6/site-packages/nio/service/base.py", line 221, in _create_and_configure_block
    block.do_configure(block_context)
  File "/usr/local/lib/python3.6/site-packages/nio/util/runner.py", line 79, in do_configure
    self.configure(context)
  File "/Users/sclay/nio/projects/8080/blocks/simulator/generators/counter.py", line 34, in configure
    self.attr_value().step())
ValueError: range() arg 3 must not be zero
[2018-01-11 19:39:25.745] NIO [ERROR] [main.ServiceManager] Service TestPickle failed to configure
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/niocore/core/service/process.py", line 176, in start
    ServiceProcess.CONFIGURE_TIMEOUT)
  File "/usr/local/lib/python3.6/site-packages/niocore/core/service/process.py", line 210, in _wait_for_status_notification
    raise ServiceProcess.ServiceStatusError()
niocore.core.service.process.ServiceProcess.ServiceStatusError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/niocore/core/service/manager.py", line 402, in _start_process
    process.start()
  File "/usr/local/lib/python3.6/site-packages/niocore/core/service/process.py", line 178, in start
    raise ConfigureFailure()
niocore.core.service.process.ConfigureFailure
[2018-01-11 19:39:25.748] NIO [INFO] [main.ServiceManager] Stopping service: TestPickle
[2018-01-11 19:39:25.749] NIO [ERROR] [TestPickle.Sim] Failed to stop
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nio/util/runner.py", line 114, in do_stop
    self.stop()
  File "/Users/sclay/nio/projects/8080/blocks/simulator/triggers/interval.py", line 44, in stop
    self._job.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'
[2018-01-11 19:39:25.750] NIO [ERROR] [TestPickle.Sim2] Failed to stop
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nio/util/runner.py", line 114, in do_stop
    self.stop()
  File "/Users/sclay/nio/projects/8080/blocks/simulator/triggers/interval.py", line 44, in stop
    self._job.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'
[2018-01-11 19:39:25.750] NIO [INFO] [TestPickle.LumberJack] Setting status to stopping
[2018-01-11 19:39:25.751] NIO [INFO] [TestPickle.LumberJack] Setting status to stopped
[2018-01-11 19:39:25.752] NIO [ERROR] [TestPickle.ThreadedPoolExecutorRouter] Failed to stop
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nio/util/runner.py", line 114, in do_stop
    self.stop()
  File "/usr/local/lib/python3.6/site-packages/nio/router/base.py", line 168, in stop
    self._diagnostic_manager.do_stop()
AttributeError: 'NoneType' object has no attribute 'do_stop'
[2018-01-11 19:39:26.750] NIO [ERROR] [main.WebHandler] Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/niocore/core/service/process.py", line 176, in start
    ServiceProcess.CONFIGURE_TIMEOUT)
  File "/usr/local/lib/python3.6/site-packages/niocore/core/service/process.py", line 210, in _wait_for_status_notification
    raise ServiceProcess.ServiceStatusError()
niocore.core.service.process.ServiceProcess.ServiceStatusError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/niocore/modules/web/cherrypy/handler.py", line 83, in _do_callback
    handler_callback(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/niocore/components/rest/handlers/collection.py", line 32, in on_get
    return sub_item.on_get(req, resp)
  File "/usr/local/lib/python3.6/site-packages/niocore/components/rest/handlers/resource.py", line 124, in on_get
    self.on_command(resp, command, params)
  File "/usr/local/lib/python3.6/site-packages/niocore/components/rest/handlers/resource.py", line 171, in on_command
    self.set_response_output(resp, command.execute(body))
  File "/usr/local/lib/python3.6/site-packages/niocore/core/service/api/command.py", line 50, in execute
    args)
  File "/usr/local/lib/python3.6/site-packages/niocore/core/service/manager.py", line 163, in on_service_command
    self._start_service(item.config, True)
  File "/usr/local/lib/python3.6/site-packages/niocore/core/service/manager.py", line 396, in _start_service
    self._start_process(process)
  File "/usr/local/lib/python3.6/site-packages/niocore/core/service/manager.py", line 407, in _start_process
    raise e
  File "/usr/local/lib/python3.6/site-packages/niocore/core/service/manager.py", line 402, in _start_process
    process.start()
  File "/usr/local/lib/python3.6/site-packages/niocore/core/service/process.py", line 178, in start
    raise ConfigureFailure()
niocore.core.service.process.ConfigureFailure
```

To simulate a signal of the same value {'sim': 2} for example, the simulator must be set with start=stop=2 and step=a non-zero integer. The python range function does not support a step of 0.

**Comment by mattdodge** [comment]
What do you expect to happen with step 0? Just spit out a single number every single time? I doubt that using the Counter generator is what you want to be using in this case.

I could maybe be convinced that there is a valid use case for that (e.g. spitting out `{"sim": 2}` every time like your example) but I would probably advise a user to use an IdentityIntervalSimulator followed by a Modifier in this case.

**Comment by ssclay** [comment]
With a step of 0, I would expect it to be the start number repeated. I agree with using an IdentitiyIntervalSimulator and a modifier as a solution, but if the Counter Simulators don't support a step of 0, then I think it should be documented with better error messages, or the block should not be allowed to be configured that way.

**Comment by mattdodge** [comment]
The block isn't allowed to be configured that way. That's why the configure method raises an exception and your service is failing to start. I would be ok with a PR that does what you are suggesting though, spits out the same number over and over again

**Comment by ssclay** [comment]
Agreed. I'll work on a pr for that. Thanks.
